In [31]:

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [56]:
from tml.model.pipeline import Pipeline, ModelHandler
from tml.models.model import BinaryClassificationLightning
from tml.data.load_data import load_and_preprocess_data


In [3]:
# Prepare the data
cols = range(1, 42+1)
input_dim = len(cols) - 1
input_path = '../data/test1.csv'
load_dict =load_and_preprocess_data(input_path, cols)
dataset = load_dict['test_set']
data = dataset[:, 1:]
hard_targets = dataset[:, 0]



Start Loading Data!
Loading Data Done!
Start Preparing Data!
Data Preparation Done!


In [57]:
model_instance = BinaryClassificationLightning(input_dim=41, nb_classes=1, dropout_rate_train=0.5, dropout_rate_pred=0.5, learning_rate=0.001)

# OR

model_class = BinaryClassificationLightning
model_config = {
    "input_dim": 41,
    "nb_classes": 1,
    "dropout_rate_train": 0.5,
    "dropout_rate_pred": 0.5,
    "learning_rate": 0.001
}

In [58]:
out1 = load_dict['out1']
out2_var = load_dict['out2_var']

In [59]:
# Initialize the pipeline
model_handler = ModelHandler(model_instance=model_instance, model_class=model_class, model_config=model_config)
pipeline = Pipeline(model_handler, data, hard_targets, max_epochs=2)





In [60]:
# model_class(**model_config)

In [61]:
pipeline.run(n_steps=2)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name           | Type                      | Params | Mode 
---------------------------------------------------------------------
0 | model          | BinaryClassificationModel | 2.6 K  | train
1 | loss_fn        | BCELoss                   | 0      | train
2 | train_accuracy | BinaryAccuracy            | 0      | train
---------------------------------------------------------------------
2.6 K     Trainable params
0         Non-trainable params
2.6 K     Total params
0.010     Total estimated model params size (MB)
12        Modules in train mode
0         Modules in eval mode


Seed: 42
Level 1 init: subset 43
Level 1 training: subset 43
Epoch 1: 100%|██████████| 52/52 [00:00<00:00, 169.49it/s, v_num=2, train_loss=0.627, train_accuracy=0.621]

`Trainer.fit` stopped: `max_epochs=2` reached.


Epoch 1: 100%|██████████| 52/52 [00:00<00:00, 168.30it/s, v_num=2, train_loss=0.627, train_accuracy=0.621]
Level 1 predict: subset 43
Pruning: subset 43
Level 2 init: subset 43


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name           | Type                      | Params | Mode 
---------------------------------------------------------------------
0 | model          | BinaryClassificationModel | 2.6 K  | train
1 | loss_fn        | BCELoss                   | 0      | train
2 | train_accuracy | BinaryAccuracy            | 0      | train
---------------------------------------------------------------------
2.6 K     Trainable params
0         Non-trainable params
2.6 K     Total params
0.010     Total estimated model params size (MB)
12        Modules in train mode
0         Modules in eval mode


Level 2 training: subset 43
Epoch 1: 100%|██████████| 51/51 [00:00<00:00, 169.46it/s, v_num=2, train_loss=0.637, train_accuracy=0.602]

`Trainer.fit` stopped: `max_epochs=2` reached.


Epoch 1: 100%|██████████| 51/51 [00:00<00:00, 168.38it/s, v_num=2, train_loss=0.637, train_accuracy=0.602]
Level 2 predict: subset 43
Level 2 prediction with dropout: subset 43


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name           | Type                      | Params | Mode 
---------------------------------------------------------------------
0 | model          | BinaryClassificationModel | 2.6 K  | train
1 | loss_fn        | BCELoss                   | 0      | train
2 | train_accuracy | BinaryAccuracy            | 0      | train
---------------------------------------------------------------------
2.6 K     Trainable params
0         Non-trainable params
2.6 K     Total params
0.010     Total estimated model params size (MB)
12        Modules in train mode
0         Modules in eval mode


Seed: 43
Level 1 init: subset 44
Level 1 training: subset 44
Epoch 1: 100%|██████████| 52/52 [00:00<00:00, 168.69it/s, v_num=2, train_loss=0.644, train_accuracy=0.622]

`Trainer.fit` stopped: `max_epochs=2` reached.


Epoch 1: 100%|██████████| 52/52 [00:00<00:00, 167.48it/s, v_num=2, train_loss=0.644, train_accuracy=0.622]
Level 1 predict: subset 44
Pruning: subset 44
Level 2 init: subset 44


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name           | Type                      | Params | Mode 
---------------------------------------------------------------------
0 | model          | BinaryClassificationModel | 2.6 K  | train
1 | loss_fn        | BCELoss                   | 0      | train
2 | train_accuracy | BinaryAccuracy            | 0      | train
---------------------------------------------------------------------
2.6 K     Trainable params
0         Non-trainable params
2.6 K     Total params
0.010     Total estimated model params size (MB)
12        Modules in train mode
0         Modules in eval mode


Level 2 training: subset 44
Epoch 1: 100%|██████████| 52/52 [00:00<00:00, 168.56it/s, v_num=2, train_loss=0.645, train_accuracy=0.619]

`Trainer.fit` stopped: `max_epochs=2` reached.


Epoch 1: 100%|██████████| 52/52 [00:00<00:00, 167.44it/s, v_num=2, train_loss=0.645, train_accuracy=0.619]
Level 2 predict: subset 44
Level 2 prediction with dropout: subset 44
Getting probability scores: subset 44
Getting uncertainty scores: subset 44


In [62]:
pipeline.y_pred.shape

(866446,)

In [63]:
pipeline.y_pred_all

array([0.5093195 , 0.41626525, 0.49113125, ..., 0.4673889 , 0.52091455,
       0.55037755], dtype=float32)

In [64]:
pipeline.all_vars

array([[5.49727178e-04, 6.29333360e-03, 2.99903157e-04, ...,
        1.55466318e-03, 5.32663544e-05, 1.91333401e-03],
       [1.74799562e-03, 4.79868194e-03, 1.79114693e-04, ...,
        1.11289043e-03, 1.22551091e-05, 7.03442376e-04]])

In [17]:
pipeline.out1

array([[1.        , 0.9265029 , 0.65363115],
       [1.        , 0.14029637, 0.16831593],
       [1.        , 0.28429806, 0.43855852],
       ...,
       [1.        , 0.9227524 , 0.6123927 ],
       [1.        , 0.9186627 , 0.6517285 ],
       [1.        , 0.9135904 , 0.65503734]], dtype=float32)

In [20]:
import numpy as np
all_probs = np.zeros((5, 866446))

In [23]:
all_probs[1] = pipeline.y_pred

In [27]:
all_probs[1]

array([0.62602884, 0.24449463, 0.48087469, ..., 0.57256263, 0.62974077,
       0.63808727])

In [45]:
pipeline.y_pred_dropout

array([[0.65363115, 0.16831593, 0.43855852, ..., 0.6123927 , 0.6517285 ,
        0.65503734],
       [0.65363115, 0.16831593, 0.43855852, ..., 0.6123927 , 0.6517285 ,
        0.65503734]], dtype=float32)

In [46]:
pipeline.model

BinaryClassificationLightning(
  (model): BinaryClassificationModel(
    (custom_dropout1): CustomDropout()
    (custom_dropout2): CustomDropout()
    (model): Sequential(
      (0): Linear(in_features=41, out_features=41, bias=True)
      (1): ReLU()
      (2): CustomDropout()
      (3): Linear(in_features=41, out_features=20, bias=True)
      (4): ReLU()
      (5): CustomDropout()
      (6): Linear(in_features=20, out_features=1, bias=True)
      (7): Sigmoid()
    )
  )
  (loss_fn): BCELoss()
  (train_accuracy): BinaryAccuracy()
)